<?php

/**
 * @file
 * Contains media_image_popup.module
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function media_image_popup_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the image_popup module.
    case 'help.page.media_image_popup':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module gives the popup field formatter for the media field types.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function media_image_popup_theme($existing, $type, $theme, $path) {
  return [
    'media_image_popup_details' => [
      'variables' => [
        'url_popup' => NULL,
      ],
      'path' => $path . '/templates',
      'template' => 'media-image-popup-formatter',
    ],
  ];
}

/**
 * Implements hook_page_attachments_alter().
 */
function media_image_popup_page_attachments_alter(array &$attachments) {
  // Add noindex metatag for media_image_popup render routes.
  $route_name = \Drupal::routeMatch()->getRouteName();
  $excluded_routes = [
    'media_image_popup.media_image_popup_render',
    'media_image_popup.media_image_popup_render_original'
  ];
  if (in_array($route_name, $excluded_routes)) {
    $noindex = [
      '#tag' => 'meta',
      '#attributes' => [
        'name' => 'robots',
        'content' => 'noindex'
      ]
    ]; 
    $attachments['#attached']['html_head'][] = [$noindex, 'robots'];
  }
}
